# Site settings
title: Chovatelská stanice hovawartů - Psí ranč
email: ivana@psi-ranc.cz
description: >
 Naše chovatelská stanice je výborně dostupná jak autem, tak MHD.
 Pro chov psů nabízí kvalitní infrastrukturu ve formě rozlehlého pozemku (cca 3000 m),
 velkého zastřešeného kotce s dřevěnou podlahou, průběžně monitorované zděné
 místnosti s vytápěním a hygienickým zázemím pro komfortní odchov štěňat.
 Velký důraz klademe na správnou socializaci štěňat v rodinném
 prostředí s dětmi, v přírodě a ve městě.

upsta: https://upsta.photo
# upsta: http://localhost:3000
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
repository: mikz/psi-ranc

baseurl:

assets:
  cache: true
