# Site settings
title: Psí ranč
email: ivana@psi-ranc.cz
description: >
 Naše chovatelská stanice je výborně dostupná jak autem, tak MHD.
 Pro chov psů nabízí kvalitní infrastrukturu ve formě rozlehlého pozemku (cca 3000 m),
 velkého zastřešeného kotce s dřevěnou podlahou, průběžně monitorované zděné
 místnosti s vytápěním a hygienickým zázemím pro komfortní odchov štěňat.
 Velký důraz klademe na správnou socializaci štěňat v rodinném
 prostředí s dětmi, v přírodě a ve městě.

exclude:
  - Gemfile
  - Gemfile.lock
github:
  url: http://localhost:4000

baseurl: /psi-ranc

assets:
  cache: true
